name: Publish the extension to marketplace

on:
  push:
    branches:
    - main
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install yarn globally
      run: npm i -g yarn
    - name: Install all packages with yarn
      run: yarn
    - name: Publish
      # if: startsWith(github.ref, 'refs/tags/')
      run: yarn deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
